# UI is hardcoded to 8080 atm, will get onto this soon
server.port=8080

# A2A Configuration to connect to demo-agent
mcp.enabled=true
mcp.url=http://localhost:3007

pukeko.ui.header[0].text=Galvanized Pukeko Demo (connecting to HTTP MCP server)
pukeko.ui.header[0].href=https://github.com/pukeko-robotics/galvanized-pukeko

# The security token may be provided from the environment variable
# mcp.jwt=${PUKEKO_MCP_JWT:}

# CORS Configuration
adk.web.cors.origins=*
adk.web.cors.methods=GET,POST,PUT,DELETE,OPTIONS
adk.web.cors.headers=*
adk.web.cors.allow-credentials=true

spring.main.allow-bean-definition-overriding=true
